// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzzoeuezeqohdhhnrrpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6em9ldWV6ZXFvaGRoaG5ycnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2OTcwMjksImV4cCI6MjA2NTI3MzAyOX0.9NwMxrQFDHp7NzzBoyR0vtGV7AWhibuilf6OjMC28fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);